config/routes.rb
Blog::Application.routes.draw do
  get "welcome/index"

   root "welcome#index"

 resources :menuitems

end

app/models/menuitem.rb
class Menuitem < ActiveRecord::Base

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/menuitems_controller.rb
class MenuitemsController < ApplicationController

def new
end

def create
 @menuitem = Menuitem.new(menuitem_params)
 @menuitem.save
 redirect_to @menuitem
end

def show
	@menuitem = Menuitem.find(params[:id])
end

def index
	@menuitems = Menuitem.all
end


private
	def menuitem_params
		params.require(:menuitem).permit(:title, :description, :price)
	end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/menuitems_helper.rb
module MenuitemsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/menuitems/index.html.erb
<h1>Listing Menu Items</h1>

<div class = "wrap">
<table>

  <tr>
    <th style = "width:33%">Title</th>
    <th style= "width:33%">Description</th>
    <th style= "width:33%" align="center">Price</th>
  </tr>
 
  <% @menuitems.each do |menuitem| %>
    <tr>
      <td><%= menuitem.title %></td>
      <td><%= menuitem.description %></td>
      <td align="center"><%= menuitem.price %></td>
    </tr>
  <% end %>
</table>

</div>

<p></p>
<%= link_to "Add Menu Items", new_menuitem_path %>

app/views/menuitems/new.html.erb
<h1>New Menu Item</h1>

<%=form_for :menuitem, url: menuitems_path do |f| %>
  <p>
    <%= f.label :"Dish Name" %><br>
    <%= f.text_field :title %>
  </p>
 
  <p>
    <%= f.label :"Dish Description" %><br>
    <%= f.text_area :description %>
  </p>
 
  <p>
    <%= f.label :"Dish Price" %><br>
    <%= f.text_area :price %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>


<% end %>

  <%= link_to "Back to List", menuitems_path %>

app/views/menuitems/show.html.erb
<h1> Menu Item </h1>

<p>
  <strong>Dish Name:</strong>
  <br>
  <%= @menuitem.title %>
</p>
 
<p>
  <strong>Description:</strong>
  <br>
  <%= @menuitem.description %>
</p>

<p>
  <strong>Price:</strong>
  <br>
  <%=@menuitem.price %>
</p>

<%=link_to "Back to List", menuitems_path %>

app/views/welcome/index.html.erb
<h1>Hello Tamaru!</h1>

<%= link_to "Menu Items", controller: "menuitems" %>